# Generated by Django 3.2.13 on 2022-08-16 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20220817_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesessions',
            name='course_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.coursecategory'),
        ),
    ]
