# Generated by Django 3.2.13 on 2022-08-16 23:34

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_coursesessions_course_cat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursesessions',
            old_name='course_cat',
            new_name='courseCategory',
        ),
        migrations.AlterField(
            model_name='coursesessions',
            name='course',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='CourseCategory', chained_model_field='CourseCategory', on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
