# Generated by Django 3.2.13 on 2022-08-23 16:23

from django.db import migrations, models
import streaming.models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='expire',
            field=models.DateField(default=streaming.models.expiration),
        ),
    ]
