# Generated by Django 3.2.13 on 2022-08-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpenDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednsday', 'Wednsday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=20)),
                ('start_hour', models.CharField(choices=[('0', '12 am'), ('1', '1 am'), ('2', '2 am'), ('3', '3 am'), ('4', '4 am'), ('5', '5 am'), ('6', '6 am'), ('7', '7 am'), ('8', '8 am'), ('9', '9 am'), ('10', '10 am'), ('11', '11 am'), ('12', '12 pm'), ('13', '1 pm'), ('14', '2 pm'), ('15', '3 pm'), ('16', '4 pm'), ('17', '5 pm'), ('18', '6 pm'), ('19', '7 pm'), ('20', '8 pm'), ('21', '9 pm'), ('22', '10 pm'), ('23', '11 pm')], default='12 am', max_length=20)),
                ('end_hour', models.CharField(choices=[('0', '12 am'), ('1', '1 am'), ('2', '2 am'), ('3', '3 am'), ('4', '4 am'), ('5', '5 am'), ('6', '6 am'), ('7', '7 am'), ('8', '8 am'), ('9', '9 am'), ('10', '10 am'), ('11', '11 am'), ('12', '12 pm'), ('13', '1 pm'), ('14', '2 pm'), ('15', '3 pm'), ('16', '4 pm'), ('17', '5 pm'), ('18', '6 pm'), ('19', '7 pm'), ('20', '8 pm'), ('21', '9 pm'), ('22', '10 pm'), ('23', '11 pm')], default='11 pm', max_length=20)),
                ('price', models.FloatField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('day', models.CharField(max_length=20)),
                ('start_hour', models.CharField(choices=[('0', '12 am'), ('1', '1 am'), ('2', '2 am'), ('3', '3 am'), ('4', '4 am'), ('5', '5 am'), ('6', '6 am'), ('7', '7 am'), ('8', '8 am'), ('9', '9 am'), ('10', '10 am'), ('11', '11 am'), ('12', '12 pm'), ('13', '1 pm'), ('14', '2 pm'), ('15', '3 pm'), ('16', '4 pm'), ('17', '5 pm'), ('18', '6 pm'), ('19', '7 pm'), ('20', '8 pm'), ('21', '9 pm'), ('22', '10 pm'), ('23', '11 pm')], max_length=20)),
                ('end_hour', models.CharField(choices=[('0', '12 am'), ('1', '1 am'), ('2', '2 am'), ('3', '3 am'), ('4', '4 am'), ('5', '5 am'), ('6', '6 am'), ('7', '7 am'), ('8', '8 am'), ('9', '9 am'), ('10', '10 am'), ('11', '11 am'), ('12', '12 pm'), ('13', '1 pm'), ('14', '2 pm'), ('15', '3 pm'), ('16', '4 pm'), ('17', '5 pm'), ('18', '6 pm'), ('19', '7 pm'), ('20', '8 pm'), ('21', '9 pm'), ('22', '10 pm'), ('23', '11 pm')], max_length=20)),
                ('price', models.FloatField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], max_length=20)),
            ],
        ),
    ]
