# Generated by Django 3.2.13 on 2022-08-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='unique_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
